### ISSUE TITLE
Add Option for Forcing Validation against Schema Draft 2020-12

### ISSUE THREAD

**Issue by BalduinLandolt** [microsoft/vscode-json-languageservice#122]
As described in #116, the error-prone validation against drafts 2019-09 and 2020-12 (the latter being the one I care about) has been dropped, instead the message is shown, that these drafts are not supported.

I understand the necessity of this behaviour, but as a user of VSCode who is relying on schemata that so happen to be draft 2020-12, it's also not very useful, and essentially forces me to use a different editor instead.  
Would it be an option to prompt the user the question, if they want to have validation anyways, acknowledging that it may result in false positives? It would presumably require a option for "force validating non-supported schema versions".

**Comment by aeschli** [comment]
The message `Draft 2019-09 schemas are not yet fully supported.` is just a warning. the validation still happens, it's just that some new properties are not recognized,

I just pushed more support and most of new properties are now supported: https://github.com/microsoft/vscode/issues/98724

**Comment by VanessaRussell** [comment]
> The message `Draft 2019-09 schemas are not yet fully supported.` is just a warning. the validation still happens, it's just that some new properties are not recognized,

This used to be true; however, it unfortunately has not been true since at least the beginning of 2022.

Using this sample schema:
``` json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "requiredProp"
    ],
    "properties": {
        "$schema": {
            "description": "Denotes which schema to validate json against",
            "$comment": "Currently only used by example to verify it is valid within VS Code",
            "type": "string"
        },
        "requiredProp": {
            "description": "Sample required prop",
            "type": "string"
        }
    }
}
```
and this sample example:
``` json
{
    "$schema": "./jsonschema.json",
    "additionalProp": "This should be an error."
}
```

within:
![image](https://user-images.githubusercontent.com/86689712/168322868-d5893146-1655-4a38-9784-57ea8eea21bc.png)

only presents the following problems:
![image](https://user-images.githubusercontent.com/86689712/168323027-8395ecfa-07a5-4b6f-89a8-9666cd765f53.png)

meanwhile, if I change the schema version to something supported such as `http://json-schema.org/draft-07/schema`, I get the list of expected validation problems:
![image](https://user-images.githubusercontent.com/86689712/168323273-2251fe7d-9fdd-423c-a6f3-1fb1c315e915.png)

**Comment by BalduinLandolt** [comment]
I can confirm that the behaviour described in detail by @VanessaRussell has already been in place by the time I opened this suggestion in early January - this is exactly why I did so. :)  
If the warning was shown alongside the actual validation, the issue would be solved for me.

But thank you for working on the new drafts, @aeschli, this will be a nice improvement to have!

**Comment by aeschli** [comment]
This got fixed in the meantime. You will only see a warning when the schema uses a feature that we don't support.
