### ISSUE TITLE
Provide a usage example in the readme

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-json-languageservice#39]

**Comment by GeorgeGkas** [comment]
What do we expect to get from the example? What should we document? Why?

**Comment by cdietschrun** [comment]
This came from an internal email request. Basically, I'm a consumer of this service via npm packages, and it was very difficult to piece together what APIs I needed to call, or what objects I needed to prepare/pass to the API to make even the one call for doValidation make sense. We think examples of this would make sense.

I'm back on this subject as I'm trying to figure out how to use the JSONSchemaService (preferable the TypeScript itself and not just the javascript) and I'm not sure how to do that, since there's no getter for the schema service inside the language service, and I'm not sure why the npm packge (vscode-json-languageservice) doesn't seem to have Typescript code for anything but the language service.

**Comment by aeschli** [comment]
JSONSchemaService is considered an implementation detail. You should only use the API's as present in the [json language service](https://github.com/microsoft/vscode-json-languageservice/blob/master/src/jsonLanguageService.ts). That's the API we keep stable and that's the APIs we want to create samples for to illustrate the usage.

**Comment by cdietschrun** [comment]
OK, sure. I really want to be able to do the schema parsing/resolution that you do in the schema service, though. What would you recommend I do?

**Comment by aeschli** [comment]
What do you want to do with the resolved scheme?
For validation, use [doValidation](https://github.com/microsoft/vscode-json-languageservice/blob/2680cc40a6bb1792a2dc3bfaace3d80c384b15ac/src/jsonLanguageService.ts#L40)

**Comment by mtangoo** [comment]
I have the same question. I want to use this with our Inhouse editor. But there are no instruction how to launch it. We want to use it over TCP not STDIO

**Comment by aeschli** [comment]
@mtangoo The JSON language *service* is just a library that you can add as a node modules, for example in a language server. You probably are looking for samples for language servers. Have a look here:
https://www.npmjs.com/package/vscode-json-languageserver#integrate
